/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as NewsroomArticleIdRouteImport } from './routes/newsroom.$articleId'
import { Route as AuditReportRouteImport } from './routes/audit.report'

const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomArticleIdRoute = NewsroomArticleIdRouteImport.update({
  id: '/newsroom/$articleId',
  path: '/newsroom/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditReportRoute = AuditReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuditRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/podcast': typeof PodcastRoute
  '/audit/report': typeof AuditReportRoute
  '/newsroom/$articleId': typeof NewsroomArticleIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/podcast': typeof PodcastRoute
  '/audit/report': typeof AuditReportRoute
  '/newsroom/$articleId': typeof NewsroomArticleIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/podcast': typeof PodcastRoute
  '/audit/report': typeof AuditReportRoute
  '/newsroom/$articleId': typeof NewsroomArticleIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/podcast'
    | '/audit/report'
    | '/newsroom/$articleId'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/podcast'
    | '/audit/report'
    | '/newsroom/$articleId'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/podcast'
    | '/audit/report'
    | '/newsroom/$articleId'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRouteWithChildren
  PodcastRoute: typeof PodcastRoute
  NewsroomArticleIdRoute: typeof NewsroomArticleIdRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom/$articleId': {
      id: '/newsroom/$articleId'
      path: '/newsroom/$articleId'
      fullPath: '/newsroom/$articleId'
      preLoaderRoute: typeof NewsroomArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/report': {
      id: '/audit/report'
      path: '/report'
      fullPath: '/audit/report'
      preLoaderRoute: typeof AuditReportRouteImport
      parentRoute: typeof AuditRoute
    }
  }
}

interface AuditRouteChildren {
  AuditReportRoute: typeof AuditReportRoute
}

const AuditRouteChildren: AuditRouteChildren = {
  AuditReportRoute: AuditReportRoute,
}

const AuditRouteWithChildren = AuditRoute._addFileChildren(AuditRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRouteWithChildren,
  PodcastRoute: PodcastRoute,
  NewsroomArticleIdRoute: NewsroomArticleIdRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
